### PR TITLE
Support arbitrary expressions in sum_cache and sum_through_many_cache

### PR DESCRIPTION
**Pull request by TSMMark**
Related Issue: #9

TODO: 

- [x] Support in sum_cache
- [x] Support in sum_through_many_cache
- [x] Use `Sequel.lit` for table names
- [x] Documentation

### CODE REVIEW

**Comment by TSMMark** [comment]
@jeremyevans all set. lmk if you need anything else

**Comment by jeremyevans** [comment]
This looks mostly good, thanks for the patch.

However, one of the rules in Sequel development is to never attempt to parse SQL, because it's basically not possible to handle even simple cases correctly.  What if summed_column is `:NEW` or `:OLD`?

The correct way to handle this is to use `Sequel.lit('NEW')` instead of `:NEW` (and likewise for `:OLD`), and remove the gsub calls.

I don't see any documentation updates for this.  I think the documentation should probably be updated to show it is possible to use expressions in addition to columns.

With those issues fixed, I'll try to test this in the next few days, and assuming no problems it will be merged and a new gem released.

**Comment by TSMMark** [comment]
Thanks for the quick feedback! All taken care of and documentation added. Looking forward to the new release

**Comment by jeremyevans** [comment]
I've released 1.3.0 with this these commits.  I rebased this pull request to get rid of the unnecessary merge commit, which is why this didn't get closed automatically.  Thanks for your work on this!

**Comment by TSMMark** [comment]
Don't mention it! Thanks for shipping so quickly. Really awesome

**Pull request closed without merging**
